micronaut:
  application:
    name: Traktor
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    authentication: cookie
    redirect:
      login-success: /
      login-failure: /login/authFailed
    oauth2:
      clients:
        google:
          client-id: '${OAUTH_CLIENT_ID}'
          client-secret: '${OAUTH_CLIENT_SECRET}'
          openid:
            issuer: 'https://accounts.google.com'
    endpoints:
      logout:
        get-allowed: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
              jws-algorithm: HS256



jackson:
  date-format: "yyyy-MM-dd'T'HH:mm:ssZ"

#datasources:
#  default:
#    type: com.zaxxer.hikari.HikariDataSource
#    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/space`}
#    username: 'space'
#    password: ''
#    driverClassName: 'org.postgresql.Driver'
#    autoCommit: false
#    hikari:
#      poolName: Hikari
#      maximum-pool-size: 10
#      data-source-properties:
#        cachePrepStmts: true
#        prepStmtCacheSize: 250
#        prepStmtCacheSqlLimit: 2048
#        useServerPrepStmts: true

flyway:
  datasources:
    default:
      enabled: true

netty:
  default:
    allocator:
      max-order: 3


