datasources:
  default:
    url: 'jdbc:h2:file:./h2db/db/traktor;DB_CLOSE_ON_EXIT=FALSE'
    username: 'traktor'
    password: 'traktor'
    driverClassName: 'org.h2.Driver'
    poolName: Hikari
    autoCommit: false

micronaut:
  server:
    cors:
      enabled: true
      configurations:
        allowedOrigins: http://localhost:4200
